routes: 
  error:
    path: '*'
    controller: IndexController
    method: ALL
    call: error

  index:
    path: '/'
    controller: StartController
    method: GET
    call: index

  start:
    path: '/start'
    controller: StartController
    method: GET
    call: start